version: '3.7'

volumes:
  bte-seal-rookery:

services:
  bte-seal-rookery:
    image: freelawproject/seal-rookery:latest
    container_name: "bte-seal-rookery"
    volumes:
      - bte-seal-rookery:${PYTHON_PACKAGES}/seal_rookery

  bte-binary-transformers-and-extractors:
    image: freelawproject/binary-transformers-and-extractors:latest
    container_name: "bte-binary-transformers-and-extractors"
    ports:
      - "5050:5050"
    depends_on:
      - bte-seal-rookery
    volumes:
      - bte-seal-rookery:${PYTHON_PACKAGES}/seal_rookery
    networks:
      - cl_net_overlay

networks:
    cl_net_overlay:
        driver: bridge
        external: true
